sonar.host.url=http://sonarqube-container:9000
sonar.projectKey=mon_projet_key_api


sonar.projectName=CrisisView_api

sonar.projectVersion=1.0


sonar.sources=.

sonar.exclusions=node_modules/**, .next/**, out/**


sonar.sourceEncoding=UTF-8

